language: scala

# These directories are cached to S3 at the end of the build
cache:
    directories:
        - $HOME/.ivy2/cache
        - $HOME/.sbt/boot/


scala:
    - 2.11.7
jdk:
    - oraclejdk8
env:
    global:
        - secure: pwACikxIuhTzrfFbkKuhaEtpcBmo/TM7nI4aURNYPRmMP48sFbufXPd6ncBDI4CtfRtw5w5aesZGtZAlQc47rCMfNH/CgLrLudx6ZlWwql4EYJHSBu3wkU8ypNnUYNHKNHt31E6qupcy6yI4eOSoAnJy+loa+cHaO3pzGgLniMq2K3LNJ0n62JHS1QW9lJ/ZCCILA2RLucaMl8fzu1PQW1YOfSfJgEGqmgcAlDkIzntDkYW6DTQnRA85Pi23axyeLiDHEQzhRiHzYFfHidMlkpOhZCSetR3j2QJKIObciDgDPHDKiGfEi/Qsjuwm8PlhsJs36o/b30jgpujXtniJ2+0/jxZb/DjwodoE1ylxB51pQR/vixtGSjcu086JloD/T7XRHw8nQloG5/5ytSZG73S0AK/9m/w22PeCbRh2wyO7/7oYUK/+UbId5c3/fWLSA1Hxd507Bd4YokhKD2XV5CCBe9NQKrpgkaVYslg1Qbcch5HntqFZhy5m6wbUKP8rvFO1t5x4T8+Mb9D+a/Bug5foVtDKExLatznSOQoPSfGtWdMRezaJU3/YLtRGzwJNF5KIR0IODWy4xMN0jBBNUklxLcTEJlROlEK1/Agp1bzRHNHKw744nmP/rv4iTKF7aXn9eEn1Je/ag/6mSoYuucKsOdAzu1U7zq4ej5yQbSY=
        - secure: SDwr+q0aXBANflxtxnDqckNAy34WYJ7sol9G71G0W2DZ2F2CDGC/27EWPQbj/MHLgNc/GLggq7duQTz3nGxWCLVOvfViL/TTSmahcY/GVorUUPHK74WbROl0siegLFc/pCN7HJuagzh61jj+R+QWQNiE6uD/n2OjqLsJg4li3fL+qqK5PxVmHVr0oM/um0/n7V3zvsQ/Dk13VWqhhxFwtRepClMKv5/pufsUsMzBo7oUIN+Ajyt/6awhqFtHhjWRa3olLbUQrGKA0wItUHHFf5JiFU/j9IzOlCLYq4DIJGCYfV8z8NjVi0iHC+KIixCGxIWhsOilaNaYTA2WIqb7oAbDhFpDuNUX9I3iG0XuzPoyLCAA3wpcX5fQRhsnHBP/kaP/2mIdnfPDqXFcgCzVnswTCGJx9SiGljk1pG0xy9Cnrr5M0jAmdIZL6CjSVtq/GkRKoMoRLqBJdf4ecaiFiV9E6utMpfr4zYjrbXwZo5G6Pd43AYyoskdS6XlBlgwOq1wZ1G+K68JDw7km9yH9/2pvQSZY4BqseDX0//iLZjL1TPnNxLzZcsOGRHsWquM4jewSxdIUr8yDtprrdoNmRxDeZ8mIoxEi9/6Klv5YtnS3Wkomr14AlOU/fvvguOvRKJEqPqugOQHhSLoqvslYyZVUdVSXK9/aWR3n1VOhscQ=
        - secure: SGGOCqaEKmRiKq5YKR3OTWrPx84rv208UBAjdz2dO+fkg7jMQabVX3OB2EuQeKGEZBa/YPQvkS9m+TmgM5/kbOoIXK/nDn5zQ6GC/XbJ2pLdnzQ0e0gL58paqpURSXG2DX/qzIxlG3Ig9j65UOgH32qM0llvChGcxdyV/HSQPKj2mmvo9BEb6d9xDaneFQMErotD4RG16gpF+SUyW5eKxS8HHtGhOywq3Vd6w29GIc7h+BD1dHrx1BrnWbdwd3g/BnYB9Ra+pUWg23fjDvGFA0rHfQhpX7aRQjjbyVbL4WLTHNqa5ibNqHacMyT4DpUkPUFt2/GIAdDyhnAI4QuvYpLjqfrGL2Jx5OD7lRRU0TgICydtLrRx11IbaayDWt24TQZCHKMp0ohFz17xUO/9CscI+DAXSwdPov4twYUtNBqLyTgMefS6Z7i5OkSSU1rg3+iGOfXZ7AZXPsxXPfyXLYmkKU0nkkPXbSlFpWNy+KpTmDPllqacoOqQy4lsswLYBmQhLLwUxkCC6ZZeMbKFeRZF58Q5YOiZvKM7uXtFmWa25vJrp5rj4r7P/qZfZ3CDzCJGEfaT1npsdQNtG80IRaTIVFKTIdmeA9a+se41j2u4E7b5ybOgIokN57ne5quXEyd2ULiNGV3LkxDtWnsLOp/7b6BmPuyooUgK7rU4AK0=
        - secure: N/g6B6aRF1bgxgHFy3MpRrqhqp+EGlzlorGvtHHQm8lP4XAT4sz3Txm03JpjT4ZMhl0vrkicQpLg7WqiiUa9c90d2auYLAMrvCSmL/C3byunZNVFBVTjnGehUCOOapbvj0JZizIqHY6rTtywmO+tSrARA4arBv5ysd/XjMU+wJvgX5zRBJeWVQWr//TA3l7WeuUiUzq+Qa02MIyKa+IaWbr17+ejjk+WlRxNnjXfJiCVKCXoxNgtYgjeuo8tF1q05fJMzmIBfZUTo8BcvdEguNgI6srZwVAvLpNvcaEBBgyit1DtgL+EGCxCj5fuoq5Vewc+gjiV5B14hYRSqYSWTbvsfvcVHr1wtrz5ZNabgmw8ogwjvlcIuYTIzlBTTM+UwbWYtTURtkaO6mWthF+EaZ5NacBYujrn3ApAuLIMr41tdFwr00ex2UXpWfkC56tNUt3urRNgoOU9Alrv8FgbrvU6MHIeOv99yhhM5N8yi/AZRFven6l49fMoqsJBGDVcZ2C3bFNnEJ2TghgQztjlo31AD1IEESAi3P9um/V8rX92nBpAye5qgH4tKYMSYu/NWOxaMWMA495NyfbIo5BdEX7862N/Pb0D/iXvtr+Q9O2t/CPN9pyjrrEVpxKuYDhSZ7Qd0cW1JbfCvBzNuuiJsqjccIkmrGBlv1G8ORKcVP0=

before_install:
 - >
    if [ "x${ENCRYPTION_PASSWORD}" != "x" ]; then
        openssl aes-256-cbc -pass pass:${ENCRYPTION_PASSWORD} -in secring.gpg.enc -out secring.gpg -d
        openssl aes-256-cbc -pass pass:${ENCRYPTION_PASSWORD} -in pubring.gpg.enc -out pubring.gpg -d
        openssl aes-256-cbc -pass pass:${ENCRYPTION_PASSWORD} -in gpg.sbt.enc -out gpg.sbt -d
    fi

script:
    - sbt -jvm-opts jvmopts -J-XX:ReservedCodeCacheSize=256M clean coverage test
    - sbt coverageReport
    - sbt coverageAggregate
    - sbt codacyCoverage
    # Tricks to avoid unnecessary cache updates
    - find $HOME/.sbt -name "*.lock" | xargs rm
    - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

after_success:
    - >
        sbt clean coverageOff 'set credentials += Credentials("Sonatype Nexus Repository Manager", "oss.sonatype.org", System.getenv("SONATYPE_USER"), System.getenv("SONATYPE_PASS"))' publish-signed
